name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["min", "lts", "1", "pre", "nightly"]  # Replace as needed with supported Julia versions
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: julia --project=@. test/runtests.jl
